### ISSUE TITLE
Question about the websocket example

### ISSUE THREAD

**Issue by rj76** [popzxc/messages-rs#11]
Hi, I'm playing with this library and I have a question about the websocket example. It implements `Notifiable` for the sink part of the connection, but the stream part is where we want to get notified about, right? Or am I understanding it totally wrong :)

**Comment by popzxc** [comment]
Hey! In this particular [example](https://github.com/popzxc/messages-rs/blob/master/examples/08_websocket.rs) we're using [`spawn_stream_forwarder`](https://docs.rs/messages/latest/messages/address/struct.Address.html#method.spawn_stream_forwarder) to automatically turn new items in the stream into messages. Which is why we need `Notifiable` for the sink part: each received message will turn into a notification that we're processing.

**Comment by rj76** [comment]
Aha! Thank you :)

Will implementing it for a stream like this work, or should it go via `Sink`? My idea was to have two actors for a websocket connection; one for sending, and one for receiving. I could of course just try, but I would like to understand :) 

```
pub struct ReceiveActor<T: Stream> {
    receiver: T,
    send_addr: Address<SendActor>
}

impl<T> ReceiveActor<T>
where
    T: Stream,
{
    pub fn new(send_addr: Address<SendActor>, receiver: T) -> Self {
        Self { receiver, send_addr }
    }
}

impl<T> Actor for ReceiveActor<T>
where
    T: Stream + Unpin + Send + Sync + Sized + 'static
{
}

#[async_trait]
impl<T> Notifiable<Result<tungstenite::Message, WsError>> for ReceiveActor<T>
where
    T: Stream + Send + Sync + Unpin + 'static,
{
    async fn notify(&mut self, input: Result<tungstenite::Message, WsError>, context: &Context<Self>) {
        let msg = match input {
            Ok(msg) => msg,
            Err(_err) => return,
        };

        // etc.
    }
}

```

**Comment by popzxc** [comment]
I guess two actors (one for sending and one for receiving) make sense in general; although it might be hard to "match" requests and responses (e.g. if you submit something to websocket and expect a response). Probably, actor system for _sending_ messages would work much better for a particular use case, e.g. [JSON RPC](https://www.jsonrpc.org/specification), where you can match requests with responses. This way, you can implement a single actor for this communication, and use [`Handler`](https://docs.rs/messages/latest/messages/handler/trait.Handler.html) to represent requests with the return value being a response.

Although if you want to turn both stream and sink into actors, I guess `Handler` would work for stream better, since you probably want to notify caller if submitting a request fails (though obviously depends on the design).

**Comment by rj76** [comment]
Sending and receiving messages are decoupled at the moment. I thought to get updates from the stream via `Notifiable`, and have the actor for sending only implement `Handler` (gets triggered from the UI or from elsewhere) and send to sink.

**Comment by popzxc** [comment]
That would probably work :)

I'll close the issue, if you have any follow-up questions -- feel free to either post here or open a new issue.
